apiVersion: batch/v1
kind: CronJob
metadata:
  name: silver
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: silver
              image: image-registry.openshift-image-registry.svc:5000/data-engineering-workshops-066351/silver:latest
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"
              env:
                - name: DB_HOST
                  value: "postgres"
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  value: "silverdb"
                - name: DB_USER
                  value: "goldlover"
                - name: DB_PASS
                  value: "postgres"
          restartPolicy: OnFailure
